#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh"

sketchybar --bar height=30 \
	color="$BAR_COLOR" \
	shadow="$SHADOW" \
	position=top \
	sticky=on \
	padding_right=15 \
	padding_left=15 \
	corner_radius="$CORNER_RADIUS" \
	margin=5 \
	blur_radius=20 \
	notch_width=0 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/deezer.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/ram.sh"

sketchybar --update
